[build]
base = "frontend/"
publish = "build"
command = "BRAND_NAME=JSNationLive yarn build"

# command = "BRAND_NAME=reactSummit yarn build && BRAND_NAME=JSNation yarn build && BRAND_NAME=NodeDayUK yarn build && BRAND_NAME=JSNationLive yarn build"
