aliases:
  - &deps
      - "Dependencies"
  - &dependencies
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "frontend/package.json" }}

      - run:
          name: install dependencies
          command: |
            if [ ! -d "frontend/node_modules" ]; then
              cd frontend && yarn install
            fi

      - save_cache:
          paths:
            - frontend/node_modules
          key: v1-dependencies-{{ checksum "frontend/package.json" }}

version: 2

workflows:
  version: 2
  buildBrands:
    jobs:
      - "Dependencies"
      - reactSummit:
          requires: *deps
          filters:
            branches:
              only: develop

      - JSNation:
          requires: *deps
          filters:
            branches:
              only: develop

jobs:
  "Dependencies":
    steps: *dependencies

  reactSummit:
    docker:
      - image: circleci/node:10

    steps:

      - run:
          name: build website
          command: cd frontend && BRAND_NAME=reactSummit yarn build

      - run:
          name: deploy to remote
          command: |
            if [ $CIRCLE_BRANCH = "master" ]; then
              cd frontend && BRAND_NAME=reactSummit ./node_modules/.bin/gulp deploy --user $FTP_USER --password $FTP_PASSWORD
            fi
            if [ $CIRCLE_BRANCH = "develop" ]; then
              cd frontend && BRAND_NAME=reactSummit ./node_modules/.bin/gulp deploy --user $FTP_USER_DEV --password $FTP_PASSWORD_DEV
            fi

  JSNation:
    docker:
      - image: circleci/node:10

    steps:

      - run:
          name: build website
          command: cd frontend && BRAND_NAME=JSNation yarn build

      - run:
          name: deploy to remote
          command: |
            if [ $CIRCLE_BRANCH = "master" ]; then
              cd frontend && BRAND_NAME=JSNation ./node_modules/.bin/gulp deploy --user $FTP_USER --password $FTP_PASSWORD
            fi
            if [ $CIRCLE_BRANCH = "develop" ]; then
              cd frontend && BRAND_NAME=JSNation ./node_modules/.bin/gulp deploy --user $FTP_USER_DEV_JSN --password $FTP_PASSWORD_DEV_JSN
            fi