version: 2.1

commands:
  dependencies:
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "frontend/yarn.lock" }}

      - run:
          name: install dependencies
          command: |
            if [ ! -d "frontend/node_modules" ]; then
              cd frontend && yarn install --production
            fi

      - save_cache:
          paths:
            - frontend/node_modules
          key: v1-dependencies-{{ checksum "frontend/yarn.lock" }}

  build-all-brands:
    steps:
      - run:
          name: build all brands
          command: cd frontend && yarn ci-build-all

jobs:
  buildBrandsAndDeployToDev:
    docker:
      - image: circleci/node:10.24.1

    steps:
      - dependencies
      - build-all-brands
      - run:
          name: deploy to netlify
          command: |
            cd frontend
            yarn netlify deploy --auth $NETLIFY_AUTH_TOKEN --prod --site $NETLIFY_SITE_DEV

  # This command is being only called directly via API referencing this job to manually trigger production deploy to Netlify
  buildBrandsAndDeployToProd:
    docker:
      - image: circleci/node:10.24.1

    steps:
      - dependencies
      - build-all-brands
      - run:
          name: deploy to netlify
          command: |
            cd frontend
            yarn netlify deploy --auth $NETLIFY_AUTH_TOKEN --prod --site $NETLIFY_SITE_PROD
            curl -X POST -H 'Content-type: application/json' --data '{"text":"All sponsor proposals have been updated on production '$CIRCLE_BUILD_URL'"}' $SLACK_CMS_UPDATE_WEBHOOK
