# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10

    branches:
      only:
        - develop

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "frontend/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            if [ ! -d "frontend/node_modules" ]; then
              cd frontend && yarn install
            fi

      - save_cache:
          paths:
            - frontend/node_modules
          key: v1-dependencies-{{ checksum "frontend/package.json" }}

      - run:
          name: build website
          command: |
            if [ $CIRCLE_BRANCH = "master" ]; then
              cd frontend && yarn build
            fi
            if [ $CIRCLE_BRANCH = "develop" ]; then
              cd frontend && yarn build
            fi

      # Uncomment to build last year
      # - run: cd 2018 && yarn install && yarn build && cd ..

      - run:
          name: deploy to remote
          command: |
            if [ $CIRCLE_BRANCH = "master" ]; then
              cd frontend && ./node_modules/.bin/gulp deploy --user $FTP_USER --password $FTP_PASSWORD
            fi
            if [ $CIRCLE_BRANCH = "develop" ]; then
              cd frontend && ./node_modules/.bin/gulp deploy --user $FTP_USER_DEV --password $FTP_PASSWORD_DEV
            fi
